name: learn-gh-actions
on: [push]
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
          repository: palpriyanshu/library-backend
          path: backend
      - name: Testing Backend
        run: |
          cd backend
          npm install
          npm test
      - uses: actions/checkout@v2
        with:
          repository: palpriyanshu/Library-react
          path: frontend
      - name: Building frontend
        run: |
          cd frontend
          npm install
          npm run build
          mv build ../backend/
          cd ..
          rm -rf frontend
          ls ../backend
