name: learn-gh-actions
on: [push]
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - name: Clonning backend
        run: |
          git clone https://github.com/palpriyanshu/library-backend.git 2> /dev/null 
          cd library-backend
          npm install 2> /dev/null
          npm test

      - name: Clonning frontend
        run: |
          git clone https://github.com/palpriyanshu/Library-react.git 2> /dev/null 
          cd Library-react
          npm install 2> /dev/null
          npm test
          npm run build
          mv build ../library-backend/
          cd ..
          rm -rf Library-react
          ls library-backend
