name: Deploy to heroku
on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: checkout backend
        run: |
          git clone https://github.com/palpriyanshu/library-backend.git backend
          cd backend
          mkdir -p ./public
          npm install
          npm test
