name: learn-gh-actions
on: [push]
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - name: loading code
      - uses: actions/checkout@v2
      - name: setting node
      - uses: actions/setup-node@v1
      - run: npm test
