name: learn-gh-actions
on: [push]
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
          repository: palpriyanshu/library-backend
          path: backend
      - name: Testing Backend
        run: |
          cd backend
          npm install
          npm test
