name: Deploy to heroku
on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: checkout backend
        run: |
          git clone https://github.com/palpriyanshu/library-backend.git backend
          cd backend
          mkdir -p ./public
          npm install
          npm test

      - name: Create build
        run: |
          cd .. 
          git clone https://github.com/palpriyanshu/Library-react.git frontend
          cd frontend
          npm install
          npm test
          npm run build
          pwd
          mv build/ ../backend/public/.
          cd ..
